apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: node-app-svc
spec:
  type: LoadBalancer
  selector:
    app: node-app-pod
  ports:
    - port: 8080 #Port number exposed internally in cluster
      protocol: TCP
      targetPort: 8080 #Port that containers are listening on
  